/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BetterScroll: typeof import('./../components/BetterScroll.vue')['default']
    CountTo: typeof import('./../components/CountTo.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Exception: typeof import('./../components/Exception.vue')['default']
    Icon: typeof import('./../components/Icon.vue')['default']
    IEpApple: typeof import('~icons/ep/apple')['default']
    IEpDocumentCopy: typeof import('~icons/ep/document-copy')['default']
    IEpExpand: typeof import('~icons/ep/expand')['default']
    IEpFold: typeof import('~icons/ep/fold')['default']
    IEpLink: typeof import('~icons/ep/link')['default']
    IEpRefresh: typeof import('~icons/ep/refresh')['default']
    IL403: typeof import('~icons/local/403')['default']
    IL404: typeof import('~icons/local/404')['default']
    IL500: typeof import('~icons/local/500')['default']
    ILLogo: typeof import('~icons/local/logo')['default']
    IMdiFullscreen: typeof import('~icons/mdi/fullscreen')['default']
    IMdiFullscreenExit: typeof import('~icons/mdi/fullscreen-exit')['default']
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    IMdiMicrosoftExcel: typeof import('~icons/mdi/microsoft-excel')['default']
    IMdiWeatherNight: typeof import('~icons/mdi/weather-night')['default']
    IMdiWeatherSunny: typeof import('~icons/mdi/weather-sunny')['default']
    ImportExcel: typeof import('./../components/ImportExcel.vue')['default']
    Loading: typeof import('./../components/Loading.vue')['default']
    Logo: typeof import('./../components/Logo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteLink: typeof import('./../components/SiteLink.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon.vue')['default']
  }
}
